### ISSUE TITLE
Failed to load python host

### ISSUE THREAD

**Issue by FatBoyXPC** [Floobits/floobits-neovim#45]
I'm getting this error when I attempt to get this plugin working with my neovim:

```
remote/host: python3 host registered plugins []                                                                                                                                                                      
function remote#host#UpdateRemotePlugins[6]..<SNR>55_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5                                                                                                    
Plugin "/home/james/dotfiles/vim/plugged/floobits-neovim/rplugin/python/floobits" is already registered                                                                                                              
remote/host: generated rplugin manifest: /home/james/.local/share/nvim/rplugin.vim                                                                                                                                   
Press ENTER or type command to continue  
```

I also get this warning when I open neovim:
```
Floobits error: no neovim python module. Run `pip install neovim` to fix. For more info, :he nvim-python
Press ENTER or type command to continue
```

However, if I `pip install neovim` or `pip3 install neovim` (pip and pip3 are the same versoin)
```
➜  ft pip install neovim
Requirement already satisfied: neovim in /usr/lib/python3.7/site-packages (0.2.6)
Requirement already satisfied: msgpack>=0.5.0 in /usr/lib/python3.7/site-packages (from neovim) (0.5.6)
Requirement already satisfied: greenlet in /usr/lib/python3.7/site-packages (from neovim) (0.4.14)
➜  ft pip3 install neovim
Requirement already satisfied: neovim in /usr/lib/python3.7/site-packages (0.2.6)
Requirement already satisfied: msgpack>=0.5.0 in /usr/lib/python3.7/site-packages (from neovim) (0.5.6)
Requirement already satisfied: greenlet in /usr/lib/python3.7/site-packages (from neovim) (0.4.14)
➜  ft pip --version
pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)
➜  ft pip3 --version
pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)
➜  ft 
```

I'm on Arch linux if that matters, I have python2 and python3 installed.

**Comment by FatBoyXPC** [comment]
Okay, I ended up adding `g:python_host_prog` to my `init.vim` and that got rid of the above, but I'm met with a new error now:

```
remote/host: python3 host registered plugins []                                                                                                                                                                      
Encountered ModuleNotFoundError loading plugin at /home/james/dotfiles/vim/plugged/floobits-neovim/rplugin/python/floobits: No module named 'common'                                                                 
Traceback (most recent call last):                                                                                                                                                                                   
  File "/usr/lib/python3.7/site-packages/neovim/plugin/host.py", line 130, in _load                                                                                                                                  
    module = imp.load_module(name, file, pathname, descr)                                                                                                                                                            
  File "/usr/lib/python3.7/imp.py", line 244, in load_module                                                                                                                                                         
    return load_package(name, filename)                                                                                                                                                                              
  File "/usr/lib/python3.7/imp.py", line 216, in load_package                                                                                                                                                        
    return _load(spec)                                                                                                                                                                                               
  File "<frozen importlib._bootstrap>", line 696, in _load                                                                                                                                                           
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                                                                                                                  
ModuleNotFoundError: No module named 'common'                                                                                                                                                                        
remote/host: python host registered plugins []                                                                                                                                                                       
remote/host: generated rplugin manifest: /home/james/.local/share/nvim/rplugin.vim                                                                                                                                   
Press ENTER or type command to continue  
```

**Comment by Gavlooth** [comment]
I am having the exact same issue. Any updates ?

**Comment by piksel** [comment]
Yeah, it seems like the plugin does not work with python3, I am currently working on a PR

**Comment by josswright** [comment]
Any movement on this? It looks like there are some pull requests that aim to fix this?

**Comment by eterps** [comment]
Any updates on this? This seems to be essentially a complete halt concerning nvim support, right?
